# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"TemporalModelBase": "00_model.ipynb",
         "TemporalModel": "00_model.ipynb"}

modules = ["model.py"]

doc_url = "https://svenssona.github.io/runningpose/"

git_url = "https://github.com/svenssona/runningpose/tree/master/"

def custom_doc_links(name): return None
