# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"TemporalModelBase": "00_model.ipynb",
         "TemporalModel": "00_model.ipynb",
         "mpjpe": "01_loss.ipynb",
         "p_mpjpe": "01_loss.ipynb",
         "mean_velocity_error": "01_loss.ipynb",
         "Skeleton": "02_skeleton.ipynb",
         "MocapDataset": "03_mocap_dataset.ipynb",
         "Human36mDataset": "04_h36m_dataset.ipynb",
         "h36m_skeleton": "04_h36m_dataset.ipynb",
         "normalize_screen_coordinates": "05_camera.ipynb",
         "image_coordinates": "05_camera.ipynb",
         "world_to_camera": "05_camera.ipynb",
         "camera_to_world": "05_camera.ipynb",
         "project_to_2d": "05_camera.ipynb",
         "project_to_2d_linear": "05_camera.ipynb",
         "qrot": "06_quaternion.ipynb",
         "qinverse": "06_quaternion.ipynb",
         "wrap": "07_utils.ipynb",
         "deterministic_random": "07_utils.ipynb",
         "ChunkedGenerator": "08_generators.ipynb",
         "UnchunkedGenerator": "08_generators.ipynb",
         "custom_camera_params": "09_custom_dataset.ipynb",
         "CustomDataset": "09_custom_dataset.ipynb",
         "get_resolution": "14_infer_video.ipynb",
         "get_fps": "10_visualization.ipynb",
         "read_video": "14_infer_video.ipynb",
         "downsample_tensor": "10_visualization.ipynb",
         "render_animation": "10_visualization.ipynb",
         "parse_args": "14_infer_video.ipynb",
         "coco_metadata": "12_data_utils.ipynb",
         "h36m_metadata": "12_data_utils.ipynb",
         "suggest_metadata": "12_data_utils.ipynb",
         "output_prefix_2d": "13_prepare_data_2d_custom.ipynb",
         "decode": "13_prepare_data_2d_custom.ipynb",
         "main": "14_infer_video.ipynb"}

modules = ["core/model.py",
           "core/loss.py",
           "core/skeleton.py",
           "core/mocap_dataset.py",
           "core/h36m_dataset.py",
           "core/camera.py",
           "core/quaternion.py",
           "core/utils.py",
           "core/generators.py",
           "core/custom_dataset.py",
           "core/visualization.py",
           "core/arguments.py",
           "data/data_utils.py",
           "data/prepare_data_2d_custom.py",
           "inference/infer_video.py"]

doc_url = "https://svenssona.github.io/runningpose/"

git_url = "https://github.com/svenssona/runningpose/tree/master/"

def custom_doc_links(name): return None
