# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/17_format_qtmdata.ipynb (unless otherwise specified).

__all__ = ['parse_args', 'main']

# Cell
import numpy as np
import pandas as pd
import argparse
import os

# Cell
def parse_args():
    parser = argparse.ArgumentParser(description='Reformat qtmdata so that we can train.')
    parser.add_argument(
        '--data-file',
        dest='data_file',
        help='qtm text file that has been formated in matlab',
        type=str
    )
    parser.add_argument(
        '--output-dir',
        dest='output_dir',
        help='directory for reformated keypoint data (default: ./)',
        default='./',
        type=str
    )

    return parser.parse_args()

# Cell
def main(args):
    """
    Loads the qtm data then removes unwanted keypoints.
    Then it infers new keypoints adds them.
    Further we scale the dataset using a the norm vector between the root and 'SpineThoracic2'.
    """
    # Loads the textfiles
    labels_np = np.loadtxt('qtm_labels_py.txt', dtype = 'str')
    data_3D = np.loadtxt(args.data_file, dtype = 'float', delimiter= ',')

    # Reformats the data to a dataframe
    data_3D = pd.DataFrame(data_3D, index=labels_np).T

    # Remove unwanted keypoints
    data_3D = data_3D.drop(
        columns=['HeadL', 'HeadR', 'Chest', 'LThighFrontLow', 'RThighFrontLow', 'LShinFrontHigh', 'RShinFrontHigh', 'LForefoot5', 'RForefoot5', 'LHeelBack', 'RHeelBack', 'LArm', 'RArm']
    )
    # Create "new" keypoints by finding the mean between some specific keypoints
    left_elbow_3D = data_3D.loc[:, ['LElbowOut','LElbowIn']].mean(axis=1)
    right_elbow_3D = data_3D.loc[:, ['RElbowOut','RElbowIn']].mean(axis=1)

    left_wrist_3D = data_3D.loc[:, ['LWristIn','LWristOut']].mean(axis=1)
    right_wrist_3D = data_3D.loc[:, ['RWristOut','RWristIn']].mean(axis=1)

    left_knee_3D = data_3D.loc[:, ['LKneeOut','LKneeIn']].mean(axis=1)
    right_knee_3D = data_3D.loc[:, ['RKneeOut','RKneeIn']].mean(axis=1)

    left_waist_3D = data_3D.loc[:, ['WaistLFront','WaistL']].mean(axis=1)
    right_waist_3D = data_3D.loc[:, ['WaistRFront','WaistR']].mean(axis=1)

    # Remove the keypoints that was taken as a mean
    data_3D = data_3D.drop(
        columns=['LElbowOut','LElbowIn', 'RElbowOut','RElbowIn', 'LWristIn','LWristOut', 'RWristIn','RWristOut', 'LKneeIn','LKneeOut', 'RKneeIn','RKneeOut', 'WaistLFront','WaistL', 'WaistRFront','WaistR']
    )
    # Adds the new keypoint data to the dataframe
    data_3D['LElbow'] = left_elbow_3D
    data_3D['RElbow'] = right_elbow_3D
    data_3D['LWrist'] = left_wrist_3D
    data_3D['RWrist'] = right_wrist_3D
    data_3D['LKnee'] = left_knee_3D
    data_3D['RKnee'] = right_knee_3D
    data_3D['LWaist'] = left_waist_3D
    data_3D['RWaist'] = right_waist_3D

    # Convert all the data relative to the root 'WaistBack'
    data_3D = data_3D.subtract(data_3D['WaistBack'], axis=0)

    # Scale each frame with a norm vector
    data_3D_scaled = []
    for i in range(0, data_3D.shape[0], 3):
        # Calculates the scale factor for each frame
        norm_vector = np.sqrt(np.square(data_3D['SpineThoracic2'].iloc[i:i+3]).sum(axis=0))
        data_3D_scaled.append(data_3D.iloc[i:i+3].divide(norm_vector))

    # Reformat to dataframe again after all data has been scaled
    data_3D = pd.concat(data_3D_scaled, ignore_index=True)

    # Remove the y-dimension to get the 2D data for side cam.
    # OBS! This may vary between camera angels.
    data_2D = data_3D.drop(index=range(1, data_3D.shape[0], 3))

    # Creates output names that depends on the name of the data file
    data_file_name =os.path.basename(os.path.normpath(args.data_file)).rsplit(".")[0]
    out_2D = os.path.join(args.output_dir, data_file_name + '_2D_keypoints.csv')
    out_3D = os.path.join(args.output_dir, data_file_name + '_3D_keypoints.csv')

    # Save the keypoint data as csv files
    pd.DataFrame.to_csv(data_2D, path_or_buf=out_2D)
    pd.DataFrame.to_csv(data_3D, path_or_buf=out_3D)

# Cell
try: from nbdev.imports import IN_NOTEBOOK
except: IN_NOTEBOOK=False

if __name__ == '__main__' and not IN_NOTEBOOK:
    args = parse_args()
    main(args)